version: '2'
services:
  grafana:
    image: grafana/grafana
    user: "0"
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=lobo_estepario
    ports:
      - '3000:3000'
    network_mode: "host"